CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT UNIQUE COLLATE NOCASE, salt TEXT, hash TEXT, created INTEGER);
CREATE TABLE IF NOT EXISTS attempts (name TEXT PRIMARY KEY, n INTEGER, since INTEGER);
CREATE TABLE IF NOT EXISTS leagues (id TEXT PRIMARY KEY, module TEXT, code TEXT UNIQUE, owner TEXT, created INTEGER);
CREATE TABLE IF NOT EXISTS memberships (league TEXT, user TEXT, club TEXT, PRIMARY KEY (league, user));
