const LK=window.LFOLook;
/* Original, locally generated collectible artwork. No third-party card assets. */
(() => {
'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const EDITIONS = [
 ['potrero','Potrero','Papel de quiosco','#356858','#d6d8a3','base'],
 ['cobre','Cobre','Metal envejecido','#974a31','#edbe86','metal'],
 ['plata','Plata','Aluminio cepillado','#536574','#d9e5e4','brush'],
 ['oro','Oro de cancha','Relieve dorado','#766024','#ffe4a0','gold'],
 ['barrio','Ídolo del barrio','Trama de camiseta','#234e7a','#c7e2f0','cloth'],
 ['promesa','Primera ovación','Papel de entrada','#b96828','#f5d996','ticket'],
 ['clasico','Noche de clásico','Tinta y reflector','#80313d','#efb18e','rays'],
 ['apertura','Apertura 2008','Serigrafía festiva','#40817c','#e3e49b','confetti'],
 ['capitan','Capitán eterno','Bordado ceremonial','#514463','#dfc6a0','embroider'],
 ['copa','La vuelta olímpica','Grabado de trofeo','#306063','#ffe3a0','cup'],
 ['archivo','Archivo 2000','Fotograbado sepia','#786345','#efdbb0','news'],
 ['leyenda','Última leyenda','Lámina iridiscente','#36374a','#e7daa5','foil']
].map(([id,name,texture,ink,paper,pattern])=>({id,name,texture,ink,paper,pattern}));
const STATS = [['speed','Ritmo','RIT'],['shooting','Remate','REM'],['passing','Pase','PAS'],['dribbling','Regate','REG'],['defense','Defensa','DEF'],['physical','Físico','FIS'],['acceleration','Aceleración','ACE'],['intelligence','Lectura de juego','INT']];
const POS = ['EI','DC','ED','MI','MP','MD','MC','MCD','INT','LI','DFC','LD','POR'];
const role = p => p==='POR'?'GK':['LI','DFC','LD'].includes(p)?'DEF':['EI','DC','ED'].includes(p)?'FWD':'MID';
const uid = () => 'custom-'+crypto.randomUUID();
const num = (v,min,max,def) => Number.isFinite(Number(v)) ? Math.max(min,Math.min(max,Math.round(Number(v)))) : def;
const color = (v,def) => /^#[a-f\d]{6}$/i.test(v||'')?v:def;
const imgOK = v => typeof v==='string' && v.length<60000 && (/^data:image\/(png|jpeg|webp|svg\+xml)[;,]/.test(v) || /^(https?:\/\/|\.{0,2}\/)?[\w\/.%\-:]+\.(png|jpe?g|webp|svg)$/i.test(v));
const photoOK = v => typeof v==='string' && v.length<1700000 && /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v);
const overall = c => { const s=c.stats; const weights=role(c.position)==='GK'?{defense:3,intelligence:2,physical:2,acceleration:1}:role(c.position)==='DEF'?{defense:4,physical:2,speed:1,passing:1}:role(c.position)==='MID'?{passing:3,intelligence:2,dribbling:2,physical:1}:{shooting:3,speed:2,dribbling:2,acceleration:1}; return Math.round(Object.entries(weights).reduce((v,[k,w])=>v+s[k]*w,0)/Object.values(weights).reduce((a,b)=>a+b,0)); };
function normalize(raw) {
 if(!raw || typeof raw!=='object' || Array.isArray(raw)) throw Error('Carta no válida.');
 const pos=POS.includes(raw.position)?raw.position:'DC';
 const c={id:typeof raw.id==='string'&&/^[\w-]{1,70}$/.test(raw.id)?raw.id:uid(),name:String(raw.name||'Nuevo jugador').trim().slice(0,32)||'Nuevo jugador',club:String(raw.club||'Club del Sur').slice(0,32),country:String(raw.country||'Argentina').slice(0,25),year:num(raw.year,2000,2015,2008),number:num(raw.number,1,99,10),position:pos,edition:EDITIONS.some(e=>e.id===raw.edition)?raw.edition:'potrero',stars:num(raw.stars,1,5,4),foot:['Derecho','Izquierdo','Ambos'].includes(raw.foot)?raw.foot:'Derecho',height:num(raw.height,160,205,180),build:num(raw.build,80,120,100),skin:color(raw.skin,'#c6865d'),hair:color(raw.hair,'#30241c'),hairStyle:LK.hairIds.includes(raw.hairStyle)?raw.hairStyle:'corto',beard:LK.beardIds.includes(raw.beard)?raw.beard:'ninguna',beardColor:color(raw.beardColor,color(raw.hair,'#30241c')),acc:Array.isArray(raw.acc)?[...new Set(raw.acc.filter(a=>LK.accIds.includes(a)))].slice(0,5):[],kit:color(raw.kit,'#e7dfc5'),accent:color(raw.accent,'#285f75'),shorts:color(raw.shorts,'#263746'),boots:color(raw.boots,'#242622'),pattern:['rayas','banda','lisa'].includes(raw.pattern)?raw.pattern:'rayas',pose:LK.poseIds.includes(raw.pose)?raw.pose:'carrera',angle:num(raw.angle,-90,90,-12),photo:photoOK(raw.photo)?raw.photo:null,crest:imgOK(raw.crest)?raw.crest:null,flag:imgOK(raw.flag)?raw.flag:null,stats:{},zones:{}};
 {const N=window.LFONations,n=N&&N.get(c.country);if(n)c.country=n.name;}
 STATS.forEach(([k])=>c.stats[k]=num(raw.stats?.[k],1,99,75)); POS.forEach(p=>c.zones[p]=num(raw.zones?.[p],0,2,0)); c.zones[pos]=2; return c;
}
let A, T, library=[], custom=[], assignments={}, current=null, activeTab='identity', showBack=false, filter='all', search='', positionFilter='all', sorting='edition', onlyCustom=false, page='collection', paintVersion=0;
const KEY='lfo-cromos-v1';
let storageWarning='';
try {const s=JSON.parse(localStorage.getItem(KEY)||'{}');custom=(Array.isArray(s.cards)?s.cards:[]).slice(0,60).map(normalize);if(s.assignments&&typeof s.assignments==='object')for(const [key,value] of Object.entries(s.assignments)) if(/^([0-9]|1[0-9]|2[01])$/.test(key)&&typeof value==='string') assignments[key]=value;}catch(e){storageWarning='No se pudo leer el álbum guardado. Podés importar una copia JSON.';}
function persist(nextCustom=custom,nextAssignments=assignments){try{localStorage.setItem(KEY,JSON.stringify({version:1,cards:nextCustom,assignments:nextAssignments}));return true;}catch(e){notify('No hay espacio para guardar. Exportá el álbum y eliminá algunas fotos.');return false;}}
function notify(s){A.notify(s);}
function edition(c){return EDITIONS.find(e=>e.id===c.edition)||EDITIONS[0];}
function modelDispose(m){if(!m)return;m.root.removeFromParent();const gs=new Set(),ms=new Set(),ts=new Set();m.root.traverse(o=>{if(o.geometry)gs.add(o.geometry);for(const material of (Array.isArray(o.material)?o.material:o.material?[o.material]:[])){ms.add(material);Object.values(material).forEach(v=>{if(v?.isTexture)ts.add(v);});}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());}
function appearance(m,c){
 m.root.scale.set(c.height/197*c.build/100,c.height/197,c.height/197);
 m.head.material.color.set(c.skin);
 const hair=m.body.children.find(o=>o.isMesh&&Math.abs(o.position.y-1.82)<.001);
 if(hair){hair.material.color.set(c.hair);hair.visible=c.hairStyle!=='rapado';hair.scale.y=c.hairStyle==='largo'?1.8:.95;}
 const tex=document.createElement('canvas');tex.width=tex.height=256;const x=tex.getContext('2d');x.fillStyle=c.kit;x.fillRect(0,0,256,256);x.fillStyle=c.accent;
 if(c.pattern==='rayas'){for(let i=0;i<256;i+=64)x.fillRect(i,0,29,256);}else if(c.pattern==='banda'){x.beginPath();x.moveTo(0,0);x.lineTo(48,0);x.lineTo(256,210);x.lineTo(256,256);x.lineTo(210,256);x.closePath();x.fill();}
 for(let y=0;y<256;y+=3){x.fillStyle='rgba(255,255,240,.06)';x.fillRect(0,y,256,1);} const map=new T.CanvasTexture(tex);map.colorSpace=T.SRGBColorSpace;if(m.torso.material.map)m.torso.material.map.dispose();m.torso.material.map=map;m.torso.material.color.set('#ffffff');m.torso.material.needsUpdate=true;
 for(const leg of [m.leftLeg,m.rightLeg]) {const upper=leg.pivot.children.find(o=>o.isMesh);if(upper)upper.material.color.set(c.shorts);const sock=leg.lower.children.find(o=>o.isMesh);if(sock)sock.material.color.set(c.accent);}
 m.leftBoot.material.color.set(c.boots);m.rightBoot.material.color.set(c.boots);
 LK.decorate(T,m,c);
}
let studio=null, studioFailure=false, studioModel=null;
function ensureStudio(){if(studio||studioFailure)return studio;try{const renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setSize(460,610);renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;const scene=new T.Scene(),camera=new T.PerspectiveCamera(29,460/610,.1,25);camera.position.set(0,1.05,3.8);camera.lookAt(0,.96,0);scene.add(new T.HemisphereLight('#fff4de','#52614c',2.2));const key=new T.DirectionalLight('#fff2d8',3.2);key.position.set(-3,5,5);scene.add(key);const rim=new T.DirectionalLight('#acdbe8',2);rim.position.set(3,2,-1);scene.add(rim);studio={renderer,scene,camera};return studio;}catch(e){studioFailure=true;return null;}}
function portrait(c){const s=ensureStudio();if(!s||!A.view)return null;modelDispose(studioModel);const p={...A.match.players[9],id:9,name:c.name,number:c.number,role:role(c.position),scale:c.height/197};const m=A.view.createPlayer(p);m.root.removeFromParent();s.scene.add(m.root);appearance(m,c);m.root.position.set(0,0,0);m.root.rotation.y=c.angle*Math.PI/180;
 if(c.pose==='carrera'){m.leftLeg.pivot.rotation.x=-.5;m.rightLeg.pivot.rotation.x=.4;m.rightLeg.lower.rotation.x=.6;m.leftArm.pivot.rotation.x=.5;m.rightArm.pivot.rotation.x=-.55;m.leftArm.lower.rotation.x=-.6;m.rightArm.lower.rotation.x=-.7;m.body.rotation.z=.04;}
 if(c.pose==='victoria'){m.leftArm.pivot.rotation.z=2.55;m.rightArm.pivot.rotation.z=-2.55;m.leftArm.lower.rotation.x=-.2;m.rightArm.lower.rotation.x=-.2;}
 const ph=LK.pose(m,c)||{};s.camera.position.set(0,1.05+((ph.look||.96)-.96),ph.dist||3.8);s.camera.lookAt(0,ph.look||.96,0);studioModel=m;s.renderer.render(s.scene,s.camera);return s.renderer.domElement.toDataURL('image/png');}
const portraitCache=new Map(), imageCache=new Map(), cardCache=new Map();
function image(src){if(!src)return Promise.resolve(null);if(imageCache.has(src))return imageCache.get(src);const p=new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>resolve(null);i.src=src;});imageCache.set(src,p);if(imageCache.size>110)imageCache.delete(imageCache.keys().next().value);return p;}
function portraitKey(c){return JSON.stringify([c.name,c.number,c.height,c.build,c.skin,c.hair,c.hairStyle,c.beard,c.beardColor,c.acc,c.kit,c.accent,c.shorts,c.boots,c.pattern,c.pose,c.angle]);}
function getPortrait(c){const key=portraitKey(c);if(!portraitCache.has(key)){portraitCache.set(key,portrait(c));if(portraitCache.size>80)portraitCache.delete(portraitCache.keys().next().value);}return portraitCache.get(key);}
function seeded(seed){return ()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
function polygon(ctx,points,fill,stroke,width=1){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function star(ctx,x,y,r,fill){polygon(ctx,Array.from({length:10},(_,i)=>{let a=i*Math.PI/5-Math.PI/2,d=i%2?r*.43:r;return [x+Math.cos(a)*d,y+Math.sin(a)*d];}),fill,'#433723',1.5);}
function text(ctx,str,x,y,size,color,font='800',align='left',max){ctx.textAlign=align;ctx.fillStyle=color;ctx.font=`${font} ${size}px "Barlow Condensed", "Arial Narrow", sans-serif`;ctx.fillText(str,x,y,max);}
function texture(ctx,e,back){const rand=seeded(e.id.split('').reduce((a,v)=>a+v.charCodeAt(0),81));
 const grad=ctx.createLinearGradient(0,0,600,840);grad.addColorStop(0,e.paper);grad.addColorStop(.2,e.ink);grad.addColorStop(.48,e.ink);grad.addColorStop(.82,e.paper);grad.addColorStop(1,e.ink);ctx.fillStyle=grad;ctx.fillRect(12,12,576,816);
 ctx.save();ctx.beginPath();ctx.rect(19,19,562,802);ctx.clip();
 const p=e.pattern;ctx.strokeStyle=e.paper+'60';ctx.lineWidth=1;
 if(['base','cloth','embroider'].includes(p)){for(let x=10;x<620;x+=p==='embroider'?12:8){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,840);ctx.stroke();}for(let y=0;y<860;y+=p==='cloth'?4:12){ctx.strokeStyle=y%8?e.paper+'50':e.ink+'aa';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(600,y+4);ctx.stroke();}}
 if(['metal','brush','gold'].includes(p)){for(let i=0;i<2200;i++){const y=rand()*840;ctx.strokeStyle=rand()>.5?'#ffefd426':'#201b2326';ctx.beginPath();ctx.moveTo(rand()*600,y);ctx.lineTo(rand()*600,y+(p==='metal'?5:0));ctx.stroke();}}
 if(['gold','cup','embroider'].includes(p)){for(let y=-50;y<920;y+=75)for(let x=-20;x<650;x+=70){ctx.strokeStyle=e.paper+'42';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y,25,38,Math.PI/4,0,Math.PI*2);ctx.ellipse(x,y,25,38,-Math.PI/4,0,Math.PI*2);ctx.stroke();}}
 if(['rays','ticket','confetti'].includes(p)){for(let i=0;i<55;i++){const a=i*Math.PI*2/55;polygon(ctx,[[330,440],[330+950*Math.cos(a),440+950*Math.sin(a)],[330+950*Math.cos(a+.025),440+950*Math.sin(a+.025)]],i%2?e.paper+'3a':'#ffffff17');}}
 if(p==='confetti'){for(let i=0;i<180;i++){ctx.save();ctx.translate(rand()*600,rand()*840);ctx.rotate(rand()*6.3);ctx.fillStyle=['#eee39a99','#e7987899','#193d3766'][i%3];ctx.fillRect(0,0,5+rand()*8,12);ctx.restore();}}
 if(p==='foil'){const g=ctx.createLinearGradient(0,0,600,750);['#acebdd','#e1bded','#f5ddb1','#92c6dd','#e1a9a2','#cee298','#bed1f2'].forEach((v,i)=>g.addColorStop(i/6,v));ctx.globalAlpha=.6;ctx.fillStyle=g;ctx.fillRect(15,15,570,810);ctx.globalAlpha=1;for(let i=-800;i<700;i+=14){ctx.strokeStyle=i%28?'#fff5':'#30355466';ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i+840,840);ctx.stroke();}for(let y=0;y<840;y+=60)for(let x=0;x<600;x+=60){polygon(ctx,[[x,y-20],[x+20,y],[x,y+20],[x-20,y]],null,'#fff7');}}
 if(p==='news'){ctx.globalAlpha=.17;for(let y=20;y<850;y+=14)text(ctx,'ARCHIVO DE CANCHA  ·  LA PASIÓN NO SE RETIRA  ·  FÚTBOL',25,y,12,'#271c13','500');ctx.globalAlpha=1;}
 if(p==='ticket'){ctx.setLineDash([5,6]);ctx.strokeStyle='#ffedd199';ctx.lineWidth=2;ctx.strokeRect(31,35,535,770);ctx.setLineDash([]);}
 // Deterministic ink grain and worn paper edges, retained in PNG exports.
 for(let i=0;i<14500;i++){ctx.fillStyle=i%3?'rgba(23,25,17,.09)':'rgba(255,247,212,.2)';ctx.fillRect(rand()*600,rand()*840,rand()*1.7+.4,rand()*2+.5);}ctx.restore();
 ctx.strokeStyle='#fff5d3';ctx.lineWidth=4;ctx.strokeRect(12,12,576,816);ctx.strokeStyle='#3d483c';ctx.lineWidth=1;ctx.strokeRect(20,20,560,800);
 if(back){ctx.fillStyle='#f0e5cdeb';ctx.fillRect(28,28,544,784);}
}
function badge(ctx,x,y,r,e,label){ctx.save();ctx.shadowColor='#101a194d';ctx.shadowBlur=5;polygon(ctx,Array.from({length:48},(_,i)=>{let a=i*Math.PI/24;let d=i%2?r-5:r;return[x+Math.cos(a)*d,y+Math.sin(a)*d];}),e.paper,e.ink,2);ctx.shadowBlur=0;ctx.strokeStyle=e.ink;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r-10,0,Math.PI*2);ctx.stroke();text(ctx,label,x,y+11,34,e.ink,'800','center');ctx.restore();}
function pitch(ctx,c,x,y,w,h){ctx.fillStyle='#294b35';ctx.fillRect(x,y,w,h);for(let i=0;i<7;i++){ctx.fillStyle=i%2?'#ffffff06':'#00000008';ctx.fillRect(x,y+i*h/7,w,h/7);}POS.forEach((p,i)=>{const col=i===12?1:i%3,row=Math.floor(i/3),xx=x+10+col*(w-20)/3,yy=y+10+row*(h-20)/5,ww=(w-20)/3,hh=(h-20)/5;const l=c.zones[p];ctx.fillStyle=l===2?'#8cd35cdf':l===1?'#8cd35c55':'#17332166';ctx.fillRect(xx+3,yy+3,ww-6,hh-6);text(ctx,p,xx+ww/2,yy+hh/2+6,19,l===2?'#16331f':'#e1e7cd','700','center');});ctx.strokeStyle='#eaf0cd99';ctx.lineWidth=2;ctx.strokeRect(x+5,y+5,w-10,h-10);ctx.beginPath();ctx.moveTo(x+5,y+h/2);ctx.lineTo(x+w-5,y+h/2);ctx.stroke();ctx.beginPath();ctx.arc(x+w/2,y+h/2,w*.12,0,Math.PI*2);ctx.stroke();ctx.strokeRect(x+w*.3,y+5,w*.4,h*.13);ctx.strokeRect(x+w*.3,y+h-h*.13-5,w*.4,h*.13);}
const LFO_LOGO='equiposfut/ligadefutbolonlinelogo.png';
async function lfoLogo(ctx,x,y,size){const i=await image(LFO_LOGO);if(i)ctx.drawImage(i,160,155,1330,1330,x,y,size,size);}
async function drawCard(canvas,c,back=false){const e=edition(c),ctx=canvas.getContext('2d');canvas.width=600;canvas.height=840;ctx.fillStyle='#e9dfc3';ctx.fillRect(0,0,600,840);texture(ctx,e,back);
 if(back){text(ctx,'LFO / ARCHIVO DE TRIBUNA',47,59,17,e.ink,'800');await lfoLogo(ctx,511,20,48);ctx.fillStyle=e.ink;ctx.fillRect(43,73,514,55);text(ctx,c.name.toUpperCase(),58,112,32,e.paper,'800','left',480);text(ctx,`${c.club.toUpperCase()} · ${c.year}`,47,156,18,e.ink,'600','left',500);text(ctx,'MAPA DE CANCHA',47,201,27,e.ink);text(ctx,'ATAQUE ↑',553,197,15,e.ink,'600','right');pitch(ctx,c,112,220,376,310);text(ctx,'■ IDEAL',112,554,17,'#477638');text(ctx,'■ ALTERNATIVA',268,554,17,'#7c9565');text(ctx,'Posiciones editables · 2 niveles de dominio',300,581,16,e.ink,'500','center');
 STATS.forEach(([k,label],i)=>{const x=i%2?321:52,y=620+Math.floor(i/2)*31;text(ctx,label.toUpperCase(),x,y,16,e.ink,'600');text(ctx,String(c.stats[k]),x+212,y,20,e.ink,'800','right');});
 ctx.strokeStyle=e.ink;ctx.beginPath();ctx.moveTo(48,730);ctx.lineTo(552,730);ctx.stroke();text(ctx,`${c.height} CM  /  ${c.foot.toUpperCase()}  /  ${c.position}`,300,756,19,e.ink,'700','center');for(let i=0;i<5;i++)star(ctx,248+i*26,782,10,i<c.stars?e.ink:'#c6c0aa');text(ctx,'COLECCIÓN PERSONAL · SIN VALOR COMERCIAL',300,809,12,e.ink,'500','center');return;}
 // Asymmetric ticket spine and engraved stadium geometry, not a shield-card template.
 ctx.fillStyle='#eee2bfe6';ctx.fillRect(29,28,41,783);ctx.save();ctx.translate(55,600);ctx.rotate(-Math.PI/2);text(ctx,`ARCHIVO DE TRIBUNA  /  ${c.year}  /  ${c.country.toUpperCase()}`,0,0,17,e.ink,'700','left',475);ctx.restore();for(let y=630;y<760;y+=5){ctx.fillStyle=y%10?'#2f3b27':'#2f3b2788';ctx.fillRect(39,y,22,y%15?2:3);}await lfoLogo(ctx,32,768,38);
 polygon(ctx,[[81,31],[563,31],[563,93],[103,93],[81,72]],e.ink,e.paper,2);text(ctx,e.name.toUpperCase(),101,69,31,e.paper,'800','left',396);text(ctx,`EDICIÓN ${c.year}  ·  ${e.texture.toUpperCase()}`,92,118,14,'#fff0cb','700','left',400);await lfoLogo(ctx,504,34,54);
 ctx.save();ctx.beginPath();ctx.rect(79,126,487,452);ctx.clip();text(ctx,String(c.number).padStart(2,'0'),476,490,370,e.paper+'38','800','center');
 ctx.strokeStyle=e.paper+'77';ctx.lineWidth=1.8;for(let i=0;i<8;i++){ctx.beginPath();ctx.ellipse(337,511,200+i*23,100+i*21,0,Math.PI,Math.PI*2);ctx.stroke();}for(let i=0;i<13;i++){ctx.beginPath();ctx.moveTo(325,375);ctx.lineTo(70+i*45,590);ctx.stroke();}
 ctx.fillStyle='#0c242744';ctx.fillRect(79,486,487,100);const src=c.photo||getPortrait(c),img=await image(src);if(img){const maxW=500,maxH=490,s=Math.min(maxW/img.width,maxH/img.height);const w=img.width*s,h=img.height*s;ctx.save();ctx.shadowColor='#15261b99';ctx.shadowBlur=12;ctx.shadowOffsetX=9;ctx.drawImage(img,327-w/2,584-h,w,h);ctx.restore();}else{text(ctx,'TU',330,340,100,e.paper,'800','center');text(ctx,'JUGADOR',330,420,70,e.paper,'800','center');}ctx.restore();
 badge(ctx,125,182,41,e,c.position);
 {const N=window.LFONations,fsrc=c.flag||(N&&N.flag(c.country))||'',fimg=fsrc?await image(fsrc):null;if(fimg){const fw=64,fh=Math.round(fw*fimg.height/fimg.width);ctx.save();ctx.shadowColor='#0009';ctx.shadowBlur=6;ctx.drawImage(fimg,93,238,fw,fh);ctx.restore();ctx.strokeStyle=e.paper;ctx.lineWidth=2.5;ctx.strokeRect(93,238,fw,fh);text(ctx,N?N.code(c.country):String(c.country).slice(0,3).toUpperCase(),125,238+fh+19,15,e.paper,'800','center');}
 const cimg=c.crest?await image(c.crest):null;if(cimg){const m=60,sc=Math.min(m/cimg.width,m/cimg.height),cw=cimg.width*sc,ch=cimg.height*sc;ctx.save();ctx.shadowColor='#0009';ctx.shadowBlur=6;ctx.drawImage(cimg,125-cw/2,326+(m-ch)/2,cw,ch);ctx.restore();}}
 text(ctx,'MEDIA',520,171,15,e.paper,'700','center');text(ctx,String(overall(c)),520,230,69,e.paper,'800','center');
 if(['cup','embroider','gold','foil'].includes(e.pattern)){ctx.save();ctx.translate(514,513);ctx.strokeStyle=e.paper;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-15,-22);ctx.bezierCurveTo(-20,9,20,9,15,-22);ctx.lineTo(-15,-22);ctx.moveTo(0,0);ctx.lineTo(0,15);ctx.moveTo(-13,15);ctx.lineTo(13,15);ctx.stroke();ctx.restore();}
 polygon(ctx,[[82,571],[563,552],[563,665],[82,665]],'#f3e6c5',e.ink,3);text(ctx,c.club.toUpperCase(),101,594,17,e.ink,'600','left',440);text(ctx,c.name.toUpperCase(),99,639,43,e.ink,'800','left',444);
 const main=STATS.slice(0,6);main.forEach(([k,label,short],i)=>{const x=83+i*80;const g=ctx.createLinearGradient(0,675,0,752);g.addColorStop(0,i<2?'#a44936':i<4?'#a49042':'#477b52');g.addColorStop(1,i<2?'#6a302b':i<4?'#6d602f':'#244f38');ctx.fillStyle=g;ctx.fillRect(x,678,77,74);ctx.strokeStyle='#e9d69b';ctx.lineWidth=1.5;ctx.strokeRect(x+3,681,71,68);text(ctx,String(c.stats[k]),x+39,719,37,'#fff0cc','800','center');text(ctx,short,x+39,741,16,'#f6e8bc','700','center');});
 for(let i=0;i<5;i++)star(ctx,130+i*31,782,12,i<c.stars?'#f9e2a4':'#273d3977');text(ctx,`${String(library.findIndex(v=>v.id===c.id)+1||1).padStart(3,'0')} / LFO`,548,790,19,e.paper,'700','right');
 ctx.strokeStyle='#fff7db66';ctx.lineWidth=2;ctx.strokeRect(25,25,550,790);
}
function shell(){const section=document.createElement('section');section.id='album';section.className='album';section.innerHTML=`
 <div class="album-topline"><span>LFO / ARCHIVO DE TRIBUNA</span><b>COLECCIÓN 2000—2015</b></div>
 <div class="album-hero"><div><h1>ARCHIVO<br>DE <em>TRIBUNA</em></h1><p>Álbum de cromos de jugadores. Creá los tuyos y asignalos a un equipo del simulador.</p><div class="album-actions"><button class="ink-button primary" id="new-card">＋ Crear mi cromo</button><button class="ink-button" id="import-cards">↥ Importar álbum</button><input type="file" id="import-file" accept="application/json,.json" hidden></div></div><div class="album-stamp" aria-label="12 ediciones originales"><small>ARCHIVO DE TRIBUNA</small><b>12<br>EDICIONES</b></div></div>
 <div class="album-tabs" role="tablist" aria-label="Archivo"><button class="active" data-page="collection" role="tab" aria-selected="true">EL ÁLBUM <span id="total-count">12</span></button><button data-page="custom" role="tab" aria-selected="false">MIS CROMOS <span id="custom-count">0</span></button><button data-page="stats" role="tab" aria-selected="false">JUGADORES & STATS</button></div>
 <div id="album-content"><div class="album-layout"><aside class="album-sidebar" aria-label="Filtrar edición" id="edition-filters"></aside><div><div class="album-toolbar"><input id="card-search" type="search" placeholder="Buscar jugador, club o país…" aria-label="Buscar cromos"><select id="position-filter" aria-label="Filtrar posición"><option value="all">Todas las posiciones</option><option value="GK">Arqueros</option><option value="DEF">Defensores</option><option value="MID">Mediocampistas</option><option value="FWD">Delanteros</option></select><select id="card-sort" aria-label="Ordenar cromos"><option value="edition">Orden de colección</option><option value="rating">Mayor media</option><option value="name">Nombre A—Z</option></select><button id="flip-all" class="ink-button" aria-pressed="false" title="Ver reversos tácticos">↻ Reversos</button></div><div id="album-grid" class="album-grid"></div><div class="album-bottom"><span id="result-count">12 CROMOS · 12 HISTORIAS</span><span>Seleccioná un cromo para ver el detalle</span></div></div></div></div>
 <div id="player-stats" class="stats-sheet" hidden></div><div class="album-credit">LFO · <button id="export-album">EXPORTAR MI ÁLBUM ↗</button></div>`;document.querySelector('.site-header').after(section);
 const nav=document.querySelector('.site-header nav');nav.querySelector('span.nav-active').outerHTML='<button id="match-nav">Centro de partidos</button>';nav.insertAdjacentHTML('afterbegin','<button class="album-nav nav-active" id="album-nav">Archivo de tribuna</button>');
 $('album-nav').onclick=()=>showAlbum(true);$('match-nav').onclick=()=>showAlbum(false);$('new-card').onclick=()=>openEditor(normalize({id:uid(),name:'Tu nombre',club:'Club del Sur',edition:'oro'}),true);$('import-cards').onclick=()=>$('import-file').click();$('import-file').onchange=importAlbum;$('export-album').onclick=()=>download(JSON.stringify({version:1,cards:custom},null,2),'LFO_mi_album.json','application/json');
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;onlyCustom=page==='custom';document.querySelectorAll('[data-page]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-selected',String(n===b));});$('album-content').hidden=page==='stats';$('player-stats').hidden=page!=='stats';if(page==='stats')renderStats();else renderGallery();});
 $('card-search').oninput=e=>{search=e.target.value;renderGallery();};$('position-filter').onchange=e=>{positionFilter=e.target.value;renderGallery();};$('card-sort').onchange=e=>{sorting=e.target.value;renderGallery();};$('flip-all').onclick=()=>{showBack=!showBack;$('flip-all').setAttribute('aria-pressed',String(showBack));$('flip-all').textContent=showBack?'↻ Anversos':'↻ Reversos';renderGallery();};
 $('edition-filters').innerHTML='<h3>LAS EDICIONES</h3><button data-edition="all" class="active"><span class="edition-dot" style="background:#394e39"></span>Todos los cromos<b>12</b></button>'+EDITIONS.map(e=>`<button data-edition="${e.id}"><span class="edition-dot" style="background:${e.ink}"></span>${e.name}</button>`).join('')+'<div class="paper-note"><strong>Reverso</strong>Cada cromo tiene dos caras. En el reverso figura la posición en la cancha.</div>';
 document.querySelectorAll('[data-edition]').forEach(b=>b.onclick=()=>{filter=b.dataset.edition;document.querySelectorAll('[data-edition]').forEach(n=>n.classList.toggle('active',n===b));renderGallery();});
 const dialog=document.createElement('dialog');dialog.id='card-editor';dialog.className='atelier';dialog.setAttribute('aria-labelledby','editor-title');document.body.append(dialog);dialog.addEventListener('close',()=>{current=null;paintVersion++;});showAlbum(true);
}
function showAlbum(yes){$('album').hidden=!yes;document.body.classList.toggle('album-open',yes);$('album-nav').classList.toggle('nav-active',yes);$('match-nav').classList.toggle('nav-active',!yes);if(yes){if(A.match.running){A.match.running=false;A.refresh();}if(lfoCareerCards().length+samples.length+custom.length!==library.length)renderGallery();}else{requestAnimationFrame(()=>A.view?.resize());}window.scrollTo(0,0);}
let galleryVersion=0;
const lfoCareerCards=()=>{try{return (window.lfoManagerPlayers?window.lfoManagerPlayers():[]).map(managerCard).filter(Boolean);}catch(e){return [];}};
async function renderGallery(){const version=++galleryVersion;const careerCards=lfoCareerCards();library=[...samples,...careerCards,...custom];$('total-count').textContent=library.length;$('custom-count').textContent=custom.length;document.querySelector('[data-edition="all"] b').textContent=library.length;let list=(onlyCustom?custom:library).filter(c=>(filter==='all'||c.edition===filter)&&(positionFilter==='all'||role(c.position)===positionFilter)&&`${c.name} ${c.club} ${c.country}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));if(sorting==='rating')list.sort((a,b)=>overall(b)-overall(a));if(sorting==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));
 $('result-count').textContent=`${list.length} CROMOS · ${onlyCustom?'TU COLECCIÓN PERSONAL':(careerCards.length?'12 ORIGINALES + '+careerCards.length+' JUGADORES DE LA LIGA':'12 EDICIONES ORIGINALES')}`;
 $('album-grid').innerHTML=list.length?list.map(c=>`<article class="collectible" data-edition="${c.edition}"><button class="card-button" data-card="${c.id}" aria-label="Ver ${esc(c.name)}, ${esc(edition(c).name)}, media ${overall(c)}"><canvas width="600" height="840" aria-label="Cromo ${esc(c.name)}"></canvas></button><div class="card-caption"><div><strong>${esc(edition(c).name)}</strong><br><span>${c.position} / ${esc(c.club)}</span></div><button data-reverse="${c.id}" aria-label="Girar cromo de ${esc(c.name)}">↻</button></div></article>`).join(''):'<div class="album-empty"><h3>No hay cromos para mostrar.</h3><p>Creá tu primer cromo o probá con otro filtro.</p></div>';
 const cards=[...document.querySelectorAll('[data-card]')];cards.forEach(b=>b.onclick=()=>openEditor(library.find(c=>c.id===b.dataset.card),false));document.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>{const c=library.find(v=>v.id===b.dataset.reverse),canvas=b.closest('article').querySelector('canvas');canvas.dataset.reverse=canvas.dataset.reverse==='true'?'false':'true';drawCard(canvas,c,canvas.dataset.reverse==='true');});
 for(let i=0;i<list.length;i++){if(version!==galleryVersion)return;const canvas=cards[i].querySelector('canvas');canvas.dataset.reverse=String(showBack);const cacheKey=JSON.stringify([list[i],showBack]);if(cardCache.has(cacheKey))canvas.getContext('2d').drawImage(cardCache.get(cacheKey),0,0);else{await drawCard(canvas,list[i],showBack);const copy=document.createElement('canvas');copy.width=600;copy.height=840;copy.getContext('2d').drawImage(canvas,0,0);cardCache.set(cacheKey,copy);if(cardCache.size>90)cardCache.delete(cardCache.keys().next().value);}if(i%3===2)await new Promise(r=>setTimeout(r,0));}
}
let samples=[];
function sampleCards(){const order=[9,2,5,10,7,8,20,16,15,19,1,18],names=['Lautaro Álvarez','Julián Benítez','Facundo Sosa','Nicolás Romero','Matías Vidal','Lucas Torres','Mateo Herrera','Pablo Martín','Iván Vega','Adrián Cruz','Tomás Acosta','Diego Silva'];return EDITIONS.map((e,i)=>{const p=A.match.players[order[i]],pos=['DC','DFC','MC','EI','MP','ED','DC','MC','LI','ED','LD','MP'][i];const c=normalize({...p,id:'archive-'+e.id,name:names[i],club:p.team?'Iberia United':'Argentina FC',position:pos,edition:e.id,year:[2004,2002,2005,2007,2006,2009,2011,2008,2010,2012,2000,2015][i],skin:['#c6865d','#e3b38c','#8d5524','#f5cbb1'][i%4],hair:['#231e18','#3f2b21','#211b18'][i%3],kit:p.team?'#aa3337':'#e9e2ce',accent:p.team?'#23303a':'#5486a0',pose:i%4===0?'victoria':'carrera',angle:i%2?14:-15,stars:i>8?5:i<2?3:4,stats:{...p.stats},zones:{[pos]:2,...(pos==='DC'?{EI:1,ED:1,MP:1}:role(pos)==='MID'?{MC:1,MCD:1,MP:1}:role(pos)==='DEF'?{DFC:1,LI:1,LD:1}:{DC:1,MI:1,MD:1})}});c.zones[pos]=2;return c;});}
function renderStats(){const rows=A.match.players;$('player-stats').innerHTML=`<table><caption>PLANILLA DE JUGADORES <span class="edition-count">/ Planteles actuales · ${rows.length} jugadores</span></caption><thead><tr><th>JUGADOR / CLUB</th><th>POS.</th><th>MEDIA</th>${STATS.map(s=>`<th title="${s[1]}">${s[2]}</th>`).join('')}<th>ENERGÍA</th><th>CROMO</th></tr></thead><tbody>${rows.map(p=>{const c=playerCard(p);return `<tr><td><strong>${esc(p.name)}</strong><br><small>${esc(A.match.teams[p.team].name)} · #${p.number}</small></td><td>${c.position}</td><td class="ovr">${overall(c)}</td>${STATS.map(([k])=>`<td>${p.stats[k]}</td>`).join('')}<td>${Math.round(p.stamina)}%</td><td><button data-player="${p.id}">Crear ↗</button></td></tr>`;}).join('')}</tbody></table>`;document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>openEditor(playerCard(A.match.players[Number(b.dataset.player)]),true));}
function playerCard(p){return normalize({...p,id:uid(),position:p.role==='GK'?'POR':p.role==='DEF'?'DFC':p.role==='MID'?'MC':'DC',club:A.match.teams[p.team].name,height:p.heightM*100,stats:p.stats});}
let editing=false, editorBack=false, repaintTimer;
function openEditor(c,isEdit){current=structuredClone(c);editing=isEdit;editorBack=false;activeTab='identity';renderEditor();$('card-editor').showModal();}
function renderEditor(){const c=current,e=edition(c),isSaved=custom.some(v=>v.id===c.id);$('card-editor').innerHTML=`<header class="atelier-head"><div><small>LFO / TALLER DE CROMOS</small><h2 id="editor-title">${editing?'NUEVO CROMO':esc(c.name.toUpperCase())}</h2></div><button class="atelier-close" id="close-editor" aria-label="Cerrar editor">×</button></header><div class="atelier-body"><aside class="proof"><div class="proof-info"><span>PRUEBA DE IMPRENTA</span><span id="proof-side">01 / ANVERSO</span></div><canvas id="card-proof" width="600" height="840" aria-label="Vista previa de la carta"></canvas><div class="proof-actions"><button class="ink-button" id="flip-proof">↻ Dar vuelta</button><button class="ink-button" id="download-card">↓ PNG</button></div><small id="texture-label">${esc(e.texture)} · acabado digital original<br>600 × 840 px / anverso y reverso exportables</small></aside><div class="editor-form">${editing?`<div class="editor-tabs" role="tablist" aria-label="Personalizar cromo">${[['identity','Jugador'],['design','Edición'],['avatar','Personaje 3D'],['stats','Stats'],['zones','Cancha']].map(([id,label])=>`<button type="button" data-editor-tab="${id}" role="tab" aria-selected="${activeTab===id}" class="${activeTab===id?'active':''}">${label}</button>`).join('')}</div><div id="editor-panel" class="editor-panel"></div>`:detailMarkup(c)}</div></div><div class="editor-footer"><small>${editing?'GUARDADO LOCAL EN ESTE NAVEGADOR<br>Exportá tu álbum para conservar una copia.':'ARCHIVO DE TRIBUNA / '+esc(e.name.toUpperCase())}</small><div>${editing?'<button class="ink-button" id="cancel-edit">Cancelar</button><button class="ink-button primary" id="save-card">Guardar cromo</button>':`<button class="ink-button" id="export-card">↓ JSON</button><button class="ink-button primary" id="edit-card">${isSaved?'Editar cromo':'Personalizar copia'}</button>`}</div></div>`;
 $('close-editor').onclick=()=>$('card-editor').close();$('flip-proof').onclick=()=>{editorBack=!editorBack;repaint();};$('download-card').onclick=async()=>{await repaint();const b=await new Promise(r=>$('card-proof').toBlob(r,'image/png'));if(b)download(b,`LFO_${current.name.replace(/[^a-z0-9]/gi,'_')}_${editorBack?'reverso':'anverso'}.png`,'image/png');};
 if(editing){$('cancel-edit').onclick=()=>$('card-editor').close();$('save-card').onclick=saveCard;document.querySelectorAll('[data-editor-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.editorTab;document.querySelectorAll('[data-editor-tab]').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-selected',String(n===b));});renderPanel();});renderPanel();}else{$('edit-card').onclick=()=>{if(!custom.some(v=>v.id===current.id))current.id=uid();editing=true;renderEditor();};$('export-card').onclick=()=>download(JSON.stringify({version:1,cards:[current]},null,2),'LFO_cromo.json','application/json');$('assign-card').onclick=assignCard;$('assign-team').onchange=updateSlots;updateSlots();if($('delete-card'))$('delete-card').onclick=deleteCard;}
 repaint();}
function detailMarkup(c){return `<div class="editor-panel"><div class="album-kicker">${esc(edition(c).name.toUpperCase())}</div><h3 style="margin-top:12px">${esc(c.name)}</h3><p>${esc(c.club)} · ${esc(c.country)} · Temporada ${c.year}<br>${c.height} cm · Pie ${esc(c.foot.toLowerCase())} · ${c.stars}/5 estrellas</p><div class="readout">${STATS.map(([k,label,short])=>`<div><small>${label}</small><b>${c.stats[k]}</b></div>`).join('')}</div><div class="stat-tip"><strong>Media ${overall(c)} · ${c.position}</strong><br>Calculada con los atributos relevantes de su posición. Las estrellas y la edición son coleccionables, no dan ventajas ocultas.</div><h3 style="margin-top:24px">ASIGNAR A UN EQUIPO</h3><p>Elegí el equipo y el jugador que reemplazará. Sus atributos y personaje 3D se trasladan al simulador. Si el partido empezó, se aplicará al reiniciarlo.</p><div class="assign-row"><select id="assign-team" aria-label="Equipo"><option value="0">Argentina FC</option><option value="1">Iberia United</option></select><select id="assign-slot" aria-label="Jugador a reemplazar"></select></div><div class="detail-actions"><button class="ink-button dark" id="assign-card">＋ Incluir en el juego</button>${custom.some(v=>v.id===c.id)?'<button class="ink-button danger-button" id="delete-card">Eliminar</button>':''}</div><p class="assigned-note" id="assigned-note"></p></div>`;}
function updateSlots(){const team=Number($('assign-team').value),gk=role(current.position)==='GK';$('assign-slot').innerHTML=A.match.players.filter(p=>p.team===team&&(gk?p.index===0:p.index!==0)).map(p=>`<option value="${p.id}">${p.number} · ${esc(p.name)} (${p.role})</option>`).join('');}
function accPicker(){const groups=['cabeza','cara','cuerpo'];return '<fieldset class="acc-picker"><legend>ACCESORIOS (hasta 5)</legend>'+groups.map(g=>`<div class="acc-group"><b>${g.toUpperCase()}</b>${LK.ACCESSORIES.filter(a=>a[2]===g).map(a=>`<label class="acc-opt"><input type="checkbox" data-acc="${a[0]}" ${(current.acc||[]).includes(a[0])?'checked':''}> ${a[1]}</label>`).join('')}</div>`).join('')+'</fieldset>';}
function fields(items){return '<div class="editor-fields">'+items.join('')+'</div>';}
function input(label,key,type='text',extra=''){return `<label>${label}<input data-field="${key}" type="${type}" value="${esc(current[key])}" ${extra}></label>`;}
function select(label,key,opts){return `<label>${label}<select data-field="${key}">${opts.map(v=>{const [val,lab]=Array.isArray(v)?v:[v,v];return `<option value="${val}" ${current[key]===val?'selected':''}>${lab}</option>`;}).join('')}</select></label>`;}
function renderPanel(){const c=current,el=$('editor-panel');if(activeTab==='identity')el.innerHTML='<h3>DATOS DEL JUGADOR</h3><p>Completá la ficha del jugador. La foto es opcional: por defecto se usa el personaje 3D.</p>'+fields([input('Nombre del jugador','name','text','maxlength="32" required'),input('Club','club','text','maxlength="32"'),input('País','country','text','maxlength="25"'),input('Dorsal','number','number','min="1" max="99"'),select('Posición principal','position',POS),input('Temporada','year','number','min="2000" max="2015"'),select('Pie preferido (ficha)','foot',['Derecho','Izquierdo','Ambos']),input('Estrellas de colección','stars','number','min="1" max="5"')])+'<div class="photo-control"><strong>Tu foto, tu cromo.</strong><br>PNG transparente recomendado. JPG y WebP admitidos; máximo 5 MB.<input id="photo-file" type="file" accept="image/png,image/jpeg,image/webp"><button id="remove-photo">Quitar foto / usar personaje 3D</button></div>';
 if(activeTab==='design')el.innerHTML='<h3>ACABADO</h3><p>Doce texturas disponibles. La textura queda impresa en la imagen descargada.</p><div class="quality-grid">'+EDITIONS.map(e=>`<button class="quality-option ${e.id===c.edition?'active':''}" data-quality="${e.id}"><i style="--swatch:${e.ink}"></i><span><b>${e.name}</b><small>${e.texture}</small></span></button>`).join('')+'</div>';
 if(activeTab==='avatar')el.innerHTML='<h3>PERSONAJE 3D</h3><p>Modelo 3D del simulador. El aspecto y la altura también se aplican al jugador en la cancha.</p><div class="studio-preview"><canvas id="avatar-preview" width="460" height="610" aria-label="Personaje 3D personalizado"></canvas><small>VISTA 3D · USÁ EL CONTROL DE ÁNGULO PARA GIRAR</small></div>'+fields([input('Piel','skin','color'),input('Cabello','hair','color'),select('Corte de pelo','hairStyle',LK.HAIR),select('Barba','beard',LK.BEARDS),input('Color de barba','beardColor','color'),select('Pose del cromo','pose',LK.POSES),input('Camiseta','kit','color'),input('Color secundario','accent','color'),input('Pantalón','shorts','color'),input('Botines','boots','color'),select('Diseño de camiseta','pattern',['rayas','banda','lisa']),input('Altura (cm)','height','number','min="160" max="205"'),input('Complexión (80–120%)','build','range','min="80" max="120"'),input('Ángulo del cromo (−90° a 90°)','angle','range','min="-90" max="90"')])+accPicker();
 if(activeTab==='stats')el.innerHTML='<h3>ATRIBUTOS</h3><p>Estos ocho atributos determinan las decisiones y el rendimiento del jugador en el partido.</p><div class="stat-tip">MEDIA POR POSICIÓN <strong id="live-overall">'+overall(c)+'</strong> / 99 · '+c.position+'</div>'+STATS.map(([k,label])=>`<label class="stat-slider"><span>${label}<output id="out-${k}">${c.stats[k]}</output></span><input data-stat="${k}" type="range" min="1" max="99" value="${c.stats[k]}"></label>`).join('');
 if(activeTab==='zones')el.innerHTML='<h3>POSICIONES</h3><p>La zona principal siempre es ideal. Tocá las demás para alternar: sin dominio → alternativa → ideal. Este mapa figura en el reverso; la posición principal define el rol del jugador.</p><div class="position-map">'+POS.map(p=>`<button data-zone="${p}" data-level="${c.zones[p]}" aria-label="${p}: ${['sin dominio','alternativa','ideal'][c.zones[p]]}">${p}${c.position===p?' · P':''}</button>`).join('')+'</div><div class="legend"><span><i></i>Zona ideal</span><span><i></i>Zona alternativa</span><span>P = posición principal</span></div><div class="stat-tip" style="margin-top:18px">Las zonas alternativas son información táctica del cromo; no alteran la formación del equipo ni aplican penalizaciones ocultas.</div>';
  el.querySelectorAll('[data-acc]').forEach(cb=>cb.onchange=()=>{const set=new Set(current.acc||[]);if(cb.checked){if(set.size>=5){cb.checked=false;notify('Máximo 5 accesorios.');return;}set.add(cb.dataset.acc);}else set.delete(cb.dataset.acc);current.acc=[...set];schedulePaint();});
 el.querySelectorAll('[data-field]').forEach(input=>input.oninput=()=>{const k=input.dataset.field;current[k]=input.type==='number'||input.type==='range'?num(input.value,Number(input.min),Number(input.max),current[k]):input.value;if(k==='position')current.zones[current.position]=2;schedulePaint();});
 el.querySelectorAll('[data-quality]').forEach(b=>b.onclick=()=>{current.edition=b.dataset.quality;renderPanel();repaint();});el.querySelectorAll('[data-stat]').forEach(input=>input.oninput=()=>{current.stats[input.dataset.stat]=Number(input.value);$('out-'+input.dataset.stat).value=input.value;$('live-overall').textContent=overall(current);schedulePaint();});el.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{const p=b.dataset.zone;if(p===current.position){notify('La posición principal siempre es una zona ideal.');return;}current.zones[p]=(current.zones[p]+1)%3;renderPanel();editorBack=true;repaint();});if($('photo-file')){$('photo-file').onchange=uploadPhoto;$('remove-photo').onclick=()=>{current.photo=null;repaint();notify('La carta vuelve a usar el personaje 3D.');};}if(activeTab==='avatar')repaint();}
function schedulePaint(){clearTimeout(repaintTimer);repaintTimer=setTimeout(repaint,100);}
async function repaint(){if(!current)return;const version=++paintVersion,c=structuredClone(current),canvas=document.createElement('canvas');await drawCard(canvas,c,editorBack);if(version!==paintVersion||!current||!$('card-proof'))return;$('card-proof').getContext('2d').drawImage(canvas,0,0);$('proof-side').textContent=editorBack?'02 / REVERSO':'01 / ANVERSO';$('texture-label').textContent=edition(c).texture+' · 600 × 840 px · '+(editorBack?'Reverso táctico':'Diseño original');if($('avatar-preview')){const img=await image(getPortrait(c));if(version===paintVersion&&$('avatar-preview')&&img){const ctx=$('avatar-preview').getContext('2d');ctx.clearRect(0,0,460,610);ctx.drawImage(img,0,0,460,610);}}}
async function uploadPhoto(ev){const f=ev.target.files[0],id=current?.id;if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>5*1024*1024){notify('Usá PNG, JPG o WebP de hasta 5 MB.');return;}try{const bitmap=await createImageBitmap(f);const s=Math.min(1,800/Math.max(bitmap.width,bitmap.height)),can=document.createElement('canvas');can.width=Math.max(1,Math.round(bitmap.width*s));can.height=Math.max(1,Math.round(bitmap.height*s));can.getContext('2d').drawImage(bitmap,0,0,can.width,can.height);bitmap.close();const data=can.toDataURL('image/webp',.9);if(!photoOK(data))throw Error();if(current?.id!==id)return;current.photo=data;repaint();notify('Foto cargada. Guardá el cromo para conservarla.');}catch(e){notify('No se pudo abrir esa imagen. Probá con otra.');}}
function saveCard(){if(!current.name.trim()){notify('Dale un nombre al jugador antes de guardar.');return;}const c=normalize(current);if(!c.id.startsWith('custom-'))c.id=uid();const next=custom.filter(v=>v.id!==c.id);if(next.length>=60){notify('El álbum admite 60 cromos personalizados. Exportá o eliminá alguno.');return;}next.push(c);if(!persist(next))return;custom=next;current=c;editing=false;renderEditor();renderGallery();notify('Cromo guardado. Ya podés incluirlo en un equipo.');}
function assignCard(){let c=current;let next=custom;if(!custom.some(v=>v.id===c.id)){c=normalize({...c,id:uid()});if(custom.length>=60){notify('El álbum está completo: máximo 60 cromos personalizados.');return;}next=[...custom,c];}const slot=Number($('assign-slot').value);if(!Number.isInteger(slot)||slot<0||slot>21)return;const nextAssignments={...assignments,[slot]:c.id};if(!persist(next,nextAssignments))return;custom=next;assignments=nextAssignments;current=c;library=[...samples,...custom];if(!A.match.started){applyAssignment(slot,c);A.refresh();}renderGallery();$('assigned-note').textContent=A.match.started?'GUARDADO: se aplicará al reiniciar el partido.':'EN EL ONCE: atributos y personaje 3D aplicados.';notify(A.match.started?'Fichaje guardado para el próximo partido.':'Jugador incorporado al equipo.');}
function applyAssignment(slot,c){const p=A.match.players[slot];if(!p)return;p.name=c.name;p.number=c.number;p.stats={...c.stats};p.role=role(c.position);p.heightM=c.height/100;p.scale=c.height/197;p.collectibleId=c.id;p.preferredFoot=c.foot;p.collectionZones={...c.zones};A.match.deriveIdentity(p);if(A.view){const old=A.view.models[slot];const model=A.view.createPlayer(p);appearance(model,c);model.root.position.set(p.x,0,p.z);A.view.models[slot]=model;modelDispose(old);}}
function managerCard(p){if(!p||!p.cardData)return null;const d=p.cardData;return normalize({...d,id:'tlm-'+(p.tlmPid||p.pid||d.id||uid()),name:p.fullName||p.name,number:p.number,stats:{...p.stats},position:d.position});}
function applySaved(){if(A&&A.match&&A.match.tlmCfg)return;for(const [slot,id] of Object.entries(assignments)){const c=custom.find(c=>c.id===id);if(c)applyAssignment(Number(slot),c);}}
function deleteCard(){if(!confirm('¿Eliminar este cromo y sus asignaciones para próximos partidos? El jugador del partido actual no cambia.'))return;const next=custom.filter(v=>v.id!==current.id),nextA=Object.fromEntries(Object.entries(assignments).filter(([,id])=>id!==current.id));if(!persist(next,nextA))return;custom=next;assignments=nextA;$('card-editor').close();renderGallery();notify('Cromo eliminado.');}
function download(data,name,type){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
async function importAlbum(ev){const f=ev.target.files[0];ev.target.value='';if(!f)return;if(f.size>12*1024*1024){notify('El archivo supera los 12 MB permitidos.');return;}try{const data=JSON.parse(await f.text());if(data.version!==1||!Array.isArray(data.cards)||data.cards.length>60)throw Error('Formato no válido. Usá un JSON exportado desde el hub.');const cards=data.cards.map(v=>{if(!v?.name||!v.stats)throw Error('Faltan nombre o estadísticas.');return normalize({...v,id:uid()});});if(custom.length+cards.length>60)throw Error('El álbum admite un máximo de 60 cromos personalizados.');const next=[...custom,...cards];if(!persist(next))return;custom=next;renderGallery();notify(`${cards.length} cromos importados. No se asignan a equipos automáticamente.`);}catch(e){notify(e instanceof SyntaxError?'El archivo no contiene JSON válido.':e.message||'No se pudo importar.');}}
async function init(){A=window.lfoArchive;if(!A){setTimeout(init,60);return;}T=A.THREE;samples=sampleCards();library=[...samples,...custom];shell();await document.fonts.ready;renderGallery();const reset=A.match.reset.bind(A.match);A.match.reset=function(){reset();applySaved();};applySaved();A.refresh();if(storageWarning)notify(storageWarning);window.lfoCards={cardCanvas:async p=>{const c=managerCard(p)||(p.collectibleId&&library.find(v=>v.id===p.collectibleId))||playerCard(p),cv=document.createElement("canvas");await drawCard(cv,structuredClone(c),false);return cv;},cardInfo:p=>{const c=managerCard(p)||(p.collectibleId&&library.find(v=>v.id===p.collectibleId))||playerCard(p);return {ovr:overall(c),pos:c.position,club:c.club,stars:c.stars};},editions:EDITIONS,normalize,overall,get cards(){return library;},get assignments(){return {...assignments};},open:id=>{const c=library.find(v=>v.id===id);if(c)openEditor(c,false);}};}
init();
})();
